version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www/projet
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  php:
    build: ./.docker/php
    container_name: symfony_php
    volumes:
      - ./project:/var/www/projet
    environment:
      - PHP_MEMORY_LIMIT=512M
    networks:
      - symfony
  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - symfony

volumes:
  mysql_data:
  projet:

networks:
  symfony:
